name: Update and Rebuild NixOS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run deployment script
        run: /etc/nixos/deploy-rustimenator.sh

