name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, nixos-runner]
    steps:
    - uses: actions/checkout@v4
    - run: nix profile install . || nix profile upgrade '.*rustimenator.*'
    - run: mkdir -p ~/rustimenator-data
    - run: |
        systemctl --user daemon-reload
        systemctl --user enable rustimenator
        systemctl --user restart rustimenator

