name: Update and Rebuild NixOS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update flake lockfile
        run: nix flake update --flake /etc/nixos

      - name: Rebuild and switch NixOS configuration
        run: nixos-rebuild switch --flake /etc/nixos

