name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: nix profile install . || nix profile upgrade '.*rustimenator.*'
    - run: mkdir -p ~/rustimenator-data
    - run: |
        export XDG_RUNTIME_DIR=/run/user/$(id -u)
        export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
        /run/current-system/sw/bin/systemctl --user daemon-reload
        /run/current-system/sw/bin/systemctl --user enable rustimenator
        /run/current-system/sw/bin/systemctl --user restart rustimenator

