name: Update and Rebuild NixOS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Debug priveleges check
        run: |
          cat /proc/$$/status | grep NoNewPrivs || echo "Unable to check flag"
          sudo echo "Sudo test successful"
      - name: Run deployment script
        run: /etc/nixos/deploy-rustimenator.sh

